### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by metab0t**
Lift the restriction of sympy

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by metab0t** [comment]
@cuihantao Is the `sympy <1.12.0` restriction necessary?

**Comment by cuihantao** [comment]
Thanks @metab0t. It looks like the SymPy version restriction is no longer necessary. 

Could you help me make the quick change?

**Comment by metab0t** [comment]
> Thanks @metab0t. It looks like the SymPy version restriction is no longer necessary.
> 
> Could you help me make the quick change?

Restriction removed

**Comment by metab0t** [comment]
Currently the build fails due to upstream.
> andes 1.8.10 has requirement sympy!=1.10.0,<1.12,>=1.6, but you have sympy 1.12

**Comment by cuihantao** [comment]
Thanks! Yes, I might go ahead and merge this PR, and then roll out a new minor release with relaxed requirement.

**Pull request merged**
